### ISSUE TITLE
Open mini app with Expanded Viewport

### ISSUE THREAD

**Issue by Raxort** [deptyped/vue-telegram#10]
Hello! Right now we have **useWebAppViewport()** and **isExpanded** property, which is read only. Could you please add an ability to open the miniapp with expanded viewport (like you did for headerColor not so long ago).

My miniapp is rather long/tall and a user has to expand it every time he opens it. This extra action can be avoided by opening the app with full height by default.

**Comment by deptyped** [comment]
Hello! Unfortunately we can't make `isExpanded` reactive (like `headerColor`), because Mini Apps API allows to expand viewport, but doesn't allow to minimize it. So `isExpanded.value = true` will work, but `isExpanded.value = false` will not, which I think can be very confusing.
Now you can expand viewport in this way:
```vue
<script lang="ts" setup>
import { useWebAppViewport } from 'vue-tg'

const { expand } = useWebAppViewport()

expand()
</script>
```

By the way, what do you think about #8? This will allow to write the code above in a declarative way:

```vue
// This is not implemented  yet

<script lang="ts" setup>
import { ExpandedViewport } from 'vue-tg'
</script>

<template>
  <ExpandedViewport />
</template>
```
Is it worth to add this feature?

**Comment by Raxort** [comment]
Thanks for your reply! I will try. As for your question: as for me it doesn't really matter how to reach the goal, both ways are nice. IMO, the current way is good because it's more straightforward and it works similarly to other features. You import, then you use const and it works like other Composables. I mean it's an expected path.

But you are the boss here and you can see the bigger picture...

**Comment by Raxort** [comment]
Just tried your solution. It solves my problem. Now the app opens in an expanded viewport. Great!
Adding "force expanded" would be nice, because in my case the app is long and it doesn't require a "minimized" state.
Is there a way to make it "force expanded" right now?

**Comment by deptyped** [comment]
> Is there a way to make it "force expanded" right now?

```vue
<script lang="ts" setup>
import { useWebAppViewport } from 'vue-tg'

const { expand, onViewportChanged } = useWebAppViewport()

onViewportChanged(expand)
</script>
```
