### ISSUE TITLE
Method showPopup is not supported in version 6.0

### ISSUE THREAD

**Issue by artyom12211** [deptyped/vue-telegram#19]
Doesn't working nothing correctly.
I get
telegram-web-app.js:1754 [Telegram.WebApp] Method showPopup is not supported in version 6.0)
telegram-web-app.js:1755 Uncaught Error: WebAppMethodUnsupported

**Comment by deptyped** [comment]
Hi. Usually this error occurs if you open the site in a browser and not as a Mini App inside a Telegram app. Please provide more details on how you open the Mini App.

**Comment by artyom12211** [comment]
It makes sense yeah. Thanks for the answer !
