### ISSUE TITLE
canSendData not working

### ISSUE THREAD

**Issue by johnedstone** [deptyped/vue-telegram#23]
Here is the output of this code:
```
<template>
  <p>initData: {{ initData }}</p>
  <p>initDataUnsafe: {{ initDataUnsafe }}</p>
  <p>isPlatform: {{ isPlatform }}</p>
  <p>isPlatformUnknown: {{ isPlatformUnknown }}</p>
  <p>isReady: {{ isReady }}</p>
  <p>canSendData: {{ canSendData }}</p>
  <p>platform: {{ platform }}</p>
  <p>version: {{ version }}</p>
</template>
```

**MiniApp output**
query_id=AAHxw2*******
initDataUnsafe: { "query_id": "AAHxw2***** }
isPlatform: e=>Telegram.WebApp.platform===e
isPlatformUnknown: false
isReady: false
canSendData: false
platform: android
version: 7.2

**Why is "canSendData" false?**
Shouldn't this line of your code say ```Telegram.WebApp.initData !=""`?
```
const canSendData = !isPlatformUnknown && Telegram.WebApp.initData === ""
```

**Comment by deptyped** [comment]
This is a Telegram limitation, you can only use `Telegram.WebApp.sendData` if the web app was launched from custom keyboard:
https://core.telegram.org/bots/webapps#keyboard-button-mini-apps
`Telegram.WebApp.initData === ""` is the way to check this.

**Comment by johnedstone** [comment]
I did in fact launch it from a `Keyboard Button` [Mini Apps launched from a web_app type keyboard button can send data back to the bot in a service message....To transmit data from the user back to the bot, the Mini App can call the Telegram.WebApp.sendData method](https://core.telegram.org/bots/webapps)) which is the only way that allows for `Telegram.WebApp.sendData` with the following code from the telethon library:
```
async def web_app_button(event):
        bl = types.ReplyInlineMarkup([
            types.TypeKeyboardButtonRow([
                types.KeyboardButtonWebView('Test!', WEB_URL),
            ])])

        await event.respond("Open URL below", buttons=bl)
```

Shouldn't you be checking that there is, in fact, a string in `Telegram.WebApp.initData`?

**Comment by deptyped** [comment]
> types.ReplyInlineMarkup
As I can see you are using [inline keyboard](https://core.telegram.org/bots/webapps#inline-button-mini-apps), this is a different type of keyboard and it does not support `Telegram.WebApp.sendData`.
You need to use `types.ReplyKeyboardMarkup` to send custom keyboard.

**Comment by johnedstone** [comment]
Thanks.
Did I read the Telegram documentation incorrectly, or is this an
implementation of your library?
Thanks again.

**Comment by deptyped** [comment]
This limitation is documented in the description of the sendData method:

![IMG_20240519.jpg](https://github.com/deptyped/vue-telegram/assets/26162440/3a376630-b448-4de3-9db9-e4edb97bb46a)

https://core.telegram.org/bots/webapps#initializing-mini-apps

**Comment by johnedstone** [comment]
Let me reread... thanks!

**Comment by johnedstone** [comment]
... yes, I've mixed up the two ... thank you.... if I continue to use the inline button, did you implement `Bot API method answerWebAppQuery` that can be used with an inline button?

**Comment by deptyped** [comment]
[`answerWebAppQuery`](https://core.telegram.org/bots/api#answerwebappquery) is part of the Bot API and `vue-tg` is not a Bot API library, so you need some Bot API library like [aiogram](https://github.com/aiogram/aiogram) to use this method:
https://docs.aiogram.dev/en/dev-3.x/api/methods/answer_web_app_query.html

List of libraries for Python to work with Bot API:
https://core.telegram.org/bots/samples#python

**Comment by deptyped** [comment]
But if you are looking for a way to pass data from web app to bot, `answerWebAppQuery` method is not what you need. 
For non-replykeyboard web apps, you need to send a POST request to server to transfer data, just like in a normal web app.

**Comment by johnedstone** [comment]
Okay thanks .... I need to reread the docs.  You've cleared some things up for me.  Thanks again.  I think that you can close this issue..
