### ISSUE TITLE
Bot API 7.7

### ISSUE THREAD

**Issue by DJafari** [deptyped/vue-telegram#29]
is possible support api 7.7 methods ?
![image](https://github.com/deptyped/vue-telegram/assets/1963047/eb2e415d-bd05-4553-8968-0565db2bbe69)

**Comment by deptyped** [comment]
Hi, we have #28 but I can't test it. The latest version (10.14.4 (4931)) and beta version (10.14.4 (4930)) of Telegram Android reports that it supports version 7.6 of the API. Looks like Bot API 7.7 is not implemented in clients yet, waiting for an update.

**Comment by deptyped** [comment]
https://github.com/deptyped/vue-telegram/releases/tag/0.7.0
