### ISSUE TITLE
[Telegram.WebApp] Changing swipes behavior is not supported in version 7.6

### ISSUE THREAD

**Issue by emiljaf12345** [deptyped/vue-telegram#34]

**Comment by deptyped** [comment]
Yes, because this feature was added in Bot API 7.7. There's nothing we can do.

**Comment by emiljaf12345** [comment]
yeah, but you updated your package, why it still showing a warn?

**Comment by deptyped** [comment]
Telegram client also needs to support Bot API 7.7 for this to work.
